version: "3"

services:

  orders:
    build: ./orders
    depends_on:
      - pg
    environment:
      MONGO_HOST: mongodb
      PAYMENTS_URL: http://payments:3000
      CATALOG_URL: http://catalog:3000

  metrics:
    build: ./metrics
    depends_on:
      - pg
    environment:
      MONGO_HOST: mongodb

  payments:
    build: ./payments
    restart: always
    depends_on:
      - pg
    environment:
      PG_HOST: pg
      PG_USER: admin
      PG_PASSWORD: admin

  catalog:
    build: ./catalog
    depends_on:
      - pg
      - redis
    environment:
      REDIS_HOST: redis

  mongodb:
    image: mongo
    restart: always

  pg:
    image: postgres
    restart: always
    env_file:
      ./pg.env
    environment:
      PGDATA: /data/pg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payments


  redis:
    image: redis
    restart: always

  shop:
    build: ./shop
    depends_on:
      - pg
      - redis
      - mongodb
      - metrics
      - catalog
      - orders
      - payments
    restart: always
    environment:
      VITE_METRICS_URL: http://metrics:3000
      VITE_CATALOG_URL: http://catalog:3000
      VITE_ORDERS_URL: http://orders:3000
      VITE_PAYMENTS_URL: http://payments:3000
    ports:
      - "80:5000"

