on: 
  push:
    branches:
      - '**'
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3

      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@master
        with:
          npm_token: ${{ secrets.USE_SPRKL_CI_TOKEN }}
          setenv: false

      - run: yarn install
      - run: yarn test:e2e:sprkl
        env: 
          SPRKL_RECIPE: all

