on: 
  pull_request:
    branches:
      - '**'

jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3

      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@4ab61ee394f453789f6b6a051e23258d21a9ab7a # The actual version is parameter
        with:
          token: ${{ secrets.USE_SPRKL_CI_TOKEN }}
          setenv: false

      - run: yarn install
      - run: yarn test:e2e:sprkl
