on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@fix/pr-commits-pull
        with:
          token: ${{ secrets.USE_SPRKL_CI_TOKEN }}
          setenv: false
 
      - run: sprkl apply --log-level=debug
      

      - run: yarn install
      - run: yarn test:e2e:sprkl

