on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  install-sprkl-test:
    runs-on: ubuntu-latest
    name: Installing Sprkl Testing
    steps:

      - uses: actions/checkout@v3

      - name: Sprkl Setup
        uses: sprkl-dev/sprkl-action/setup@master
        with:
          token: ${{ secrets.USE_SPRKL_CI_TOKEN }}
          setenv: false

      - run: git rev-list -n 1 HEAD
      - run: echo $SPRKL_RECIPE
      - run: echo $SPRKL_COMMITS 
      - run: sprkl apply --log-level=debug
      

      - run: yarn install
      - run: yarn test:e2e:sprkl

